package chap10_exception;

import java.util.Scanner;

public class MethodThrow {
	// 필드
	private int x,y;
	
	private final int[] NUMBER = {1, 2, 3, 4};
	
	// 생성자
	public MethodThrow() {
		x = 1;
		y = 1;
	}
	public MethodThrow(int x, int y) {
		this.x = x;
		this.y = y;
	}
	
	// 상위 메소드(객체를 통해 메소드를 사용할때 try.catch 사용)
	// 에게 예외 처리를 요청하는 throw
	public int division() {
		return x/y;
	}
	
	// 아래의 상수가 있을때
	// private int[] NUMBER = {1, 2, 3, 4}
	// 숫자값을 입력받아와서
	// 상수의 인덱스에 접근해서 값을 return 하는 메소드 작성
	// ArrayIndexOutOfBoundsException throw로 예외처리하기
	Scanner input = new Scanner(System.in);
	private final int[] NUMBER = {1, 2, 3, 4};
	int index = input.nextInt();
	






}
